import { useQuery } from '@tanstack/react-query'
import type { Artisan } from '../types/artisan'

// Données mock — préouverture (identiques à Emergent)
const MOCK_ARTISANS: Artisan[] = [
  { id: 'artisan-1', slug: 'plomberie-martin-lyon', shop_name: 'Plomberie Martin & Fils', metier: 'Plombier', description: 'Entreprise familiale depuis 1985. Spécialistes en plomberie générale, chauffage et sanitaires. Intervention rapide 7j/7.', city: 'Lyon', postal_code: '69003', phone: '04 78 XX XX XX', is_verified: true, rating_average: 4.9, reviews_count: 127, cover_image: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800', services: ['Dépannage urgent', 'Installation sanitaire', 'Rénovation salle de bain', 'Chauffe-eau'] },
  { id: 'artisan-2', slug: 'elec-pro-marseille', shop_name: 'Élec Pro Méditerranée', metier: 'Électricien', description: 'Électriciens certifiés Qualifelec. Mise aux normes, domotique, bornes de recharge. Devis gratuit sous 24h.', city: 'Marseille', postal_code: '13008', phone: '04 91 XX XX XX', is_verified: true, rating_average: 4.8, reviews_count: 89, cover_image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800', services: ['Mise aux normes', 'Tableau électrique', 'Domotique', 'Borne de recharge'] },
  { id: 'artisan-3', slug: 'maconnerie-dupont-toulouse', shop_name: 'Maçonnerie Dupont', metier: 'Maçon', description: 'Maçonnerie traditionnelle et moderne. Construction, rénovation, extension. Travail soigné garanti.', city: 'Toulouse', postal_code: '31000', phone: '05 61 XX XX XX', is_verified: true, rating_average: 4.7, reviews_count: 64, cover_image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800', services: ['Construction neuve', 'Extension', 'Rénovation', 'Murs de clôture'] },
  { id: 'artisan-4', slug: 'carrelage-concept-nice', shop_name: 'Carrelage Concept Côte d\'Azur', metier: 'Carreleur', description: 'Pose de carrelage haut de gamme. Spécialistes grands formats, mosaïque et pierre naturelle.', city: 'Nice', postal_code: '06000', phone: '04 93 XX XX XX', is_verified: true, rating_average: 4.9, reviews_count: 112, cover_image: 'https://images.unsplash.com/photo-1615971677499-5467cbab01c0?w=800', services: ['Carrelage intérieur', 'Carrelage extérieur', 'Mosaïque', 'Pierre naturelle'] },
  { id: 'artisan-5', slug: 'peinture-artdeco-bordeaux', shop_name: 'Art\'Déco Peinture', metier: 'Peintre', description: 'Peinture décorative et technique. Ravalement, papier peint, effets décoratifs. Artisan d\'art.', city: 'Bordeaux', postal_code: '33000', phone: '05 56 XX XX XX', is_verified: true, rating_average: 4.8, reviews_count: 78, cover_image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800', services: ['Peinture intérieure', 'Peinture extérieure', 'Papier peint', 'Effets décoratifs'] },
  { id: 'artisan-6', slug: 'menuiserie-bois-nantes', shop_name: 'L\'Atelier du Bois', metier: 'Menuisier', description: 'Menuiserie sur mesure. Fabrication artisanale de meubles, cuisines, dressings et agencements.', city: 'Nantes', postal_code: '44000', phone: '02 40 XX XX XX', is_verified: true, rating_average: 5.0, reviews_count: 56, cover_image: 'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?w=800', services: ['Cuisine sur mesure', 'Dressing', 'Escalier bois', 'Mobilier'] },
  { id: 'artisan-7', slug: 'toiture-expertise-lille', shop_name: 'Toiture Expertise Nord', metier: 'Couvreur', description: 'Couverture, zinguerie et isolation de toiture. Urgence fuite 24h/24. Garantie décennale.', city: 'Lille', postal_code: '59000', phone: '03 20 XX XX XX', is_verified: true, rating_average: 4.6, reviews_count: 93, cover_image: 'https://images.unsplash.com/photo-1607400201889-565b1ee75f8e?w=800', services: ['Réfection toiture', 'Zinguerie', 'Isolation combles', 'Urgence fuite'] },
  { id: 'artisan-8', slug: 'chauffage-confort-strasbourg', shop_name: 'Chauffage Confort Plus', metier: 'Chauffagiste', description: 'Installation et entretien de systèmes de chauffage. PAC, chaudières, plancher chauffant.', city: 'Strasbourg', postal_code: '67000', phone: '03 88 XX XX XX', is_verified: true, rating_average: 4.7, reviews_count: 67, cover_image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800', services: ['Pompe à chaleur', 'Chaudière gaz', 'Plancher chauffant', 'Entretien annuel'] },
  { id: 'artisan-9', slug: 'piscine-azur-montpellier', shop_name: 'Piscines Azur Méditerranée', metier: 'Pisciniste', description: 'Construction et rénovation de piscines. Liner, béton, traitement automatique. SAV réactif.', city: 'Montpellier', postal_code: '34000', phone: '04 67 XX XX XX', is_verified: true, rating_average: 4.8, reviews_count: 45, cover_image: 'https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=800', services: ['Construction piscine', 'Rénovation', 'Traitement eau', 'Hivernage'] },
  { id: 'artisan-10', slug: 'jardin-creation-rennes', shop_name: 'Jardins & Créations', metier: 'Paysagiste', description: 'Conception et création de jardins. Terrasses, clôtures, arrosage automatique. Entretien.', city: 'Rennes', postal_code: '35000', phone: '02 99 XX XX XX', is_verified: true, rating_average: 4.9, reviews_count: 88, cover_image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800', services: ['Création jardin', 'Terrasse bois', 'Clôture', 'Arrosage automatique'] },
  { id: 'artisan-11', slug: 'clim-pro-aix', shop_name: 'Clim\'Pro Provence', metier: 'Climaticien', description: 'Installation et maintenance climatisation. Réversible, gainable, multi-split. Certification RGE.', city: 'Aix-en-Provence', postal_code: '13100', phone: '04 42 XX XX XX', is_verified: true, rating_average: 4.7, reviews_count: 52, cover_image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800', services: ['Clim réversible', 'Gainable', 'Multi-split', 'Entretien'] },
  { id: 'artisan-12', slug: 'facade-renovation-dijon', shop_name: 'Façades & Rénovation', metier: 'Façadier', description: 'Ravalement de façades, ITE, crépi. Traitement des fissures et imperméabilisation.', city: 'Dijon', postal_code: '21000', phone: '03 80 XX XX XX', is_verified: true, rating_average: 4.6, reviews_count: 41, cover_image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800', services: ['Ravalement', 'ITE', 'Crépi', 'Traitement fissures'] },
]

export function useArtisans(filters?: { metier?: string; city?: string; verified?: boolean }) {
  return useQuery({
    queryKey: ['artisans', filters],
    queryFn: async () => {
      // Pour la préouverture, on utilise les données mock
      // TODO: remplacer par GET /api/ecosystem/users quand l'API sera prête
      let result = [...MOCK_ARTISANS]
      if (filters?.metier) result = result.filter((a) => a.metier === filters.metier)
      if (filters?.city) result = result.filter((a) => a.city === filters.city)
      if (filters?.verified) result = result.filter((a) => a.is_verified)
      return result
    },
  })
}
